name: Build Ship Explorer Stereo Fix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout our files
        uses: actions/checkout@v4

      - name: Checkout UEVR headers only
        uses: actions/checkout@v4
        with:
          repository: praydog/UEVR
          ref: 4ee5c6b6162dee2291fc75f9dfc57667f6d45a2d
          path: UEVR
          submodules: false
          fetch-depth: 1

      - name: Build Ship Explorer DLL
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl /nologo /std:c++latest /EHsc /LD /I"%GITHUB_WORKSPACE%\UEVR\include" "%GITHUB_WORKSPACE%\Plugin.cpp" /Fe:"%GITHUB_WORKSPACE%\ShipExplorerStereoFix.dll"

      - name: Upload finished DLL
        uses: actions/upload-artifact@v4
        with:
          name: ShipExplorerStereoFix
          path: ShipExplorerStereoFix.dll
